language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - ./code-check.sh
script:
  - python setup.py test
install:
  - pip install pep8
  - pip install flake8
  - pip install pep8-naming
